services:
    sunmedia.query.advertisement.controller.v1:
        class: App\Controller\Query\AdvertisementController
        public: true
        arguments:
            - '@sunmedia.view_list_advertisements.service'
            - '@sunmedia.view_detail_advertisements.service'
            - '@sunmedia.advertisement.data_transformer'
            - '@logger'
            - '0'

    sunmedia.manage.advertisement.controller.v1:
        class: App\Controller\Manage\AdvertisementController
        public: true
        arguments:
            - '@sunmedia.create_advertisements.service'
            - '@sunmedia.update_advertisements.service'
            - '@sunmedia.delete_advertisements.service'
            - '@sunmedia.advertisement.data_transformer'
            - ~
            - '0'
