parameters:
    sunmedia.advertisement_model.class: 'App\Domain\Model\Advertisement'

services:
#### MYSQL
    # Advertisement
    sunmedia.persistence.advertisement.repository:
        alias: 'App\Infrastructure\Persistence\Doctrine\AdvertisementRepository'
        public: true

    App\Infrastructure\Persistence\Doctrine\AdvertisementRepository:
        public: false
        autowire: true

    # Components
    sunmedia.persistence.component.repository:
        alias: 'App\Infrastructure\Persistence\Doctrine\ComponentRepository'
        public: true

    App\Infrastructure\Persistence\Doctrine\ComponentRepository:
        public: false
        autowire: true
