parameters:
    sunmedia.advertisement_model.class: 'App\Domain\Model\Advertisement'

services:
#### MYSQL
    # Advertisement
    sunmedia.persistence.advertisement.repository:
        alias: 'App\Infrastructure\Persistence\Doctrine\AdvertisementRepository'
        public: true

    App\Infrastructure\Persistence\Doctrine\AdvertisementRepository:
        public: false
        autowire: true

    # Text
#   sunmedia.persistence.text.repository:
#       alias: 'sunmedia.text.doctrine_orm.repository'

#   sunmedia.text.doctrine_orm.repository:
#       class: 'App\Infrastructure\Persistence\Doctrine\TextComponentRepository'
#       public: false
#       factory: ['@doctrine.orm.entity_manager', getRepository]
#       arguments:
#           - '%sunmedia.advertisement_model.class%'

#   # Text
#   sunmedia.persistence.media.repository:
#       alias: 'sunmedia.media.doctrine_orm.repository'

#   sunmedia.media.doctrine_orm.repository:
#       class: 'App\Infrastructure\Persistence\Doctrine\MediaComponentRepository'
#       public: false
#       factory: ['@doctrine.orm.entity_manager', getRepository]
#       arguments:
#           - '%sunmedia.advertisement_model.class%'
