services:
    sunmedia.advertisement.data_transformer:
        class: 'App\Application\Service\DataTransformer\AdvertisementDataTransformer'

    sunmedia.advertisement.factory:
        class: 'App\Application\Service\AdvertisingFactory'

    sunmedia.view_list_advertisements.service:
        class: 'App\Application\Service\Query\ViewListOfAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'

#    sunmedia.delete_advertisements.service:
#        class: 'App\Application\Service\DeleteAdvertisementService'
#        arguments:
#            - '@sunmedia.persistence.advertisement.repository'
#            - '@sunmedia.advertisement.data_transformer'

#    sunmedia.update_advertisements.service:
#        class: 'App\Application\Service\UpdateAdvertisementService'
#        arguments:
#            - '@sunmedia.persistence.advertisement.repository'
#            - '@sunmedia.advertisement.data_transformer'

    sunmedia.create_advertisements.service:
        class: 'App\Application\Service\Manage\CreateAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'
