services:
    sunmedia.advertisement.data_transformer:
        class: 'App\Application\Service\DataTransformer\AdvertisementDataTransformer'

    sunmedia.advertisement.factory:
        class: 'App\Application\Service\AdvertisingFactory'

    sunmedia.view_list_advertisements.service:
        class: 'App\Application\Service\Query\ViewListOfAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'

    sunmedia.view_detail_advertisements.service:
        class: 'App\Application\Service\Query\ViewDetailOfAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'

    sunmedia.create_advertisements.service:
        class: 'App\Application\Service\Manage\CreateAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'

    sunmedia.update_advertisements.service:
        class: 'App\Application\Service\Manage\UpdateAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'

    sunmedia.delete_advertisements.service:
        class: 'App\Application\Service\Manage\DeleteAdvertisementService'
        arguments:
            - '@sunmedia.persistence.advertisement.repository'
            - '@sunmedia.advertisement.factory'
