App\Domain\Model\Advertisement:
    type: entity
    table: advertisements
    repositoryClass: Infrastructure\Persistence\Doctrine\AdvertisementRepository
    id:
        id:
            type: string
            generator:
            strategy: UUID
    fields:
        status:
            type: integer

    oneToMany:
        components:
            targetEntity: App\Domain\Model\Component
            mappedBy: advertisement
