App\Domain\Model\Component:
    type: entity
    inheritanceType: joined
    table: components
    repositoryClass: Infrastructure\Persistence\Doctrine\ComponentRepository
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        videos: App\Domain\Model\Video
        images: App\Domain\Model\Image
        texts: App\Domain\Model\Text
    id:
        id:
            type: string
            generator:
            strategy: UUID
    fields:
        name:
            type: string
            length: 100
        positionX:
            type: integer
        positionY:
            type: integer
        positionZ:
            type: integer
        width:
            type: integer
        height:
            type: integer

    manyToOne:
        advertisement:
            targetEntity: App\Domain\Model\Advertisement
            joinColumn:
                name: advertisment
                nullable: false
                referencedColumnName: id
            cascade: ['persist']
            referencedColumnName: advertisement_id
