sunmedia.create_adv:
    path: /advertisement
    defaults: { _controller: sunmedia.advertisement.controller.v1:view }
    methods: ['GET']
    requirements:
        _format: 'json'

#sunmedia.create_adv:
#    path: /advertisement
#    defaults: { _controller: sunmedia.advertisement.controller.v1:createAction }
#    methods: ['POST']
#    requirements:
#        _format: 'json'
