sunmedia.adv.list:
    path: /advertisement
    defaults: { _controller: sunmedia.query.advertisement.controller.v1:list }
    methods: ['GET']
    requirements:
        _format: 'json'

sunmedia.adv.detail:
    path: /advertisement/{id}
    defaults: { _controller: sunmedia.query.advertisement.controller.v1:detail }
    methods: ['GET']
    requirements:
        _format: 'json'

sunmedia.adv.create:
    path: /advertisement
    defaults: { _controller: sunmedia.manage.advertisement.controller.v1:create }
    methods: ['POST']
    requirements:
        _format: 'json'
